.\" Copyright (c) 2010 Mark Benjamin <mapcatcher.code.Markie1@dfgh.net>
.\" Fri 16 Jul 2010 11:43 AM
.\"
.\" This is free documentation; you may redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.TH MAPCATCHER 1 2010-07-16 "Linux" "Linux Programmer's Manual"
.SH NAME
mapcatcher - the debian distribution of the GMapCatcher offline map viewer
.SH DESCRIPTION
GMapCatcher downloads tiles automatically from many providers then displays
them using a custom GUI. User may view maps offline. GMapCatcher is
independent of map providers' javascript so should work even though 
the scripts may change. It also provides a downloading tool. 
.SH SUGGESTIONS AND BUG REPORTS
should be notified at http://code.google.com/p/gmapcatcher/issues
.SH Authors and Copyright Conditions
the Authors of the gmapcatcher project are listed at
http://code.google.com/p/gmapcatcher/people/list
.P
this manpage is copyright Mark Benjamin 2010
.SH INFO
.I mapcatcher 
project.
A description of the project, as well as
how to report bugs,may be found at
.P
.I http://code.google.com/p/gmapcatcher